#!/usr/bin/perl
# (c) 2001-2007 Vlado Keselj www.cs.dal.ca/~vlado
#
# $Id: starfish,v 3.7 2007/04/09 18:55:39 vlado Exp $
#
# starfish - a script for using Starfish.pm
#
# The script runs the function starfishfiles with a list of files and
# options given in the command line.
#
# For more documentation, please consult Text::Starfish.pm.

use Text::Starfish;
starfishfiles(@ARGV);
